name: test-environment
channels:
- conda-forge
dependencies:
  - python=${PYTHON}
  - pytest>=3.2.0
  - pytest-cov
  - coveralls
  - keras
  - networkx
  - numpy
  - osmnx
  - pytables
  - pandas
  - scikit-learn
  - tensorflow=1.13.1 --no-deps
  - keras=2.2.4 --no-deps
  - tensorflow-estimator --no-deps
  - grpcio=1.16.0 --no-deps